import Head from "next/head";
import { LoginCard } from "@/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jueteng</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/* <link rel='icon' href='/favicon.ico' /> */}
      </Head>
      <main className='adminLogin'>
        <LoginCard />
      </main>
    </>
  );
}
